'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),express=require('express');const {AssetLibrary}=require('../lib/assets');const {mountAssetIntake}=require('../lib/asset-intake');
test('external submissions are grouped, resumable, isolated and append-only, with link limits and revocation',async t=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'vault-intake-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.mkdir(path.join(root,'assets'));const library=new AssetLibrary(root),shares={one:{kind:'asset-upload',by:'owner'},two:{kind:'asset-upload',by:'owner'},read:{kind:'asset',by:'owner'},enabled:{kind:'asset',by:'owner',allowAssetUpload:true}};let access=true;const app=express();app.use(express.json());mountAssetIntake(app,{root,library,resolveShare:id=>shares[id]?{share:shares[id]}:{error:'gone'},allowedForOwner:()=>access?['assets']:[],saveShares(){}});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port+'/api/share/';const req=(id,suffix,method='GET',body)=>fetch(base+id+'/asset'+suffix,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 const body={name:'Test rock',sourceAssetId:'existing',collection:'Private',files:[{path:'models/rock.glb',size:5,role:'model'},{path:'notes.txt',size:0,role:'documentation'}]};assert.equal((await req('read','/intake','POST',body)).status,403);assert.equal((await req('enabled','/info')).status,200);
 for(const file of ['../secret','asset.json','CON.glb','model.glb.'])assert.equal((await req('one','/intake','POST',{...body,files:[{path:file,size:1}]})).status,400);
 const init=await req('one','/intake','POST',body);assert.equal(init.status,201);const {id}=await init.json();assert.equal((await req('two','/intake/'+id)).status,404);assert.equal((await req('one','/intake/'+id+'/finish','POST')).status,409);
 const chunk=(offset,data)=>fetch(base+'one/asset/intake/'+id+'/0?offset='+offset,{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:data});assert.equal((await chunk(0,'abc')).status,200);assert.deepEqual((await (await req('one','/intake/'+id)).json()).received,[3,0]);assert.equal((await chunk(0,'xx')).status,409);assert.equal((await chunk(3,'def')).status,400);assert.equal((await chunk(3,'de')).status,200);assert.equal((await req('one','/intake/'+id+'/finish','POST')).status,200);assert.equal((await req('one','/intake/'+id+'/finish','POST')).status,200);assert.equal((await chunk(5,'x')).status,409);
 const rows=await library.list({collection:'External assets'});assert.equal(rows.total,1);const asset=await library.get(rows.items[0].id);assert.match(asset.rel,/^assets\/External assets\//);assert.equal(asset.fileCount,2);assert.equal(asset.sourceAssetId,'external-'+id);assert.equal(await fs.readFile(path.join(root,asset.rel,'models/rock.glb'),'utf8'),'abcde');
 assert.equal((await req('one','/intake/'+id,'DELETE')).status,404);delete shares.one;assert.equal((await req('one','/intake/'+id)).status,410);access=false;assert.equal((await req('two','/intake','POST',body)).status,410);access=true;shares.two.uploadCount=200;assert.equal((await req('two','/intake','POST',body)).status,413);
});
